name: clearsky_photo_reports
description: A photo inspection app for ClearSky Roof Inspectors.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/clearsky_logo.png

