name: clearsky_photo_reports
description: A photo-based roof inspection app for insurance professionals and contractors.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

fl_chart: ^0.66.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.6
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  share_plus: ^7.2.1
  printing: ^5.12.0
  path_provider: ^2.1.3
  path: ^1.9.0
  file_picker: ^6.2.0
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.6.6
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  image_picker: ^1.0.7
  file_picker: ^6.2.0
  flutter_image_compress: ^2.2.0
  pdf: ^3.10.4
  printing: ^5.12.0
  flutter_html: ^3.0.0-beta.2
  uuid: ^4.1.0
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  http: ^1.2.1
  sqflite: ^2.3.2
  path: ^1.9.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/splash.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
