name: clearsky_photo_reports
description: A photo-based roof inspection app for insurance professionals, contractors, and adjusters.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1

  # Geolocation
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # QR Codes & URL
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.6

  # File management & sharing
  path_provider: ^2.1.3
  path: ^1.9.0
  file_picker: ^6.2.0
  share_plus: ^7.2.1
  printing: ^5.12.0

  # Firebase
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.6.6
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  image_picker: ^1.1.2

  # Local storage
  shared_preferences: ^2.2.2

  # Charts
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/splash.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
