name: clearsky_photo_reports
description: A photo inspection app for ClearSky Roof Inspectors.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  reorderables: ^0.6.0
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  path: ^1.8.3
  archive: ^3.3.3
  share_plus: ^7.2.1
  webview_flutter: ^4.13.0
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.0.0
  firebase_auth: ^4.0.0
  signature: ^5.3.0
  geolocator: ^11.0.0
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/clearsky_logo.png

