name: clearsky_photo_reports
description: A photo-based roof inspection app for insurance professionals, contractors, and adjusters.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1

  # Geolocation
  geolocator: ^14.0.1
  geocoding: ^4.0.0

  # QR Codes & URL
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.6

  # File management & sharing
  path_provider: ^2.1.2
  path: ^1.9.0
  file_picker: ^10.2.0
  share_plus: ^11.0.0
  printing: ^5.12.0
  pdf: ^3.10.8

  # Firebase
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  firebase_core: ^3.15.2
  firebase_auth: ^5.6.0
  image_picker: ^1.0.4
  google_ml_kit: ^0.16.2
  cached_network_image: ^3.3.1

  # Local storage
  shared_preferences: ^2.2.2

  # Charts
  fl_chart: ^1.0.0
  intl: ^0.20.2
  signature: ^6.3.0
  reorderables: ^0.6.0
  webview_flutter: ^4.13.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.2.1
  flutter_email_sender: ^7.0.0
  flutter_tts: ^4.2.3
  ffmpeg_kit_flutter: ^6.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2
  uuid: ^4.2.1
  speech_to_text: ^7.0.0
  http: ^1.4.0
  image: ^4.5.4
  archive: ^4.0.7
  js: ^0.6.7

  # Tutorials
  tutorial_coach_mark: ^1.3.0
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/splash.png
    - assets/icon.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
      - asset: assets/fonts/Inter-Regular.ttf
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
