name: clearsky_photo_reports
description: A photo inspection app for ClearSky Roof Inspectors.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  signature: ^5.4.1
  fl_chart: ^0.64.0
  image_picker: ^1.0.7
  http: ^1.1.0
  cloud_firestore: ^4.15.0
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.1.2
  share_plus: ^11.0.0

  # Firebase (only if needed — comment out if not using these yet)
  firebase_core: ^2.25.0
  firebase_storage: ^11.5.1
  firebase_auth: ^4.15.0
  firebase_messaging: ^14.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/clearsky_logo.png
# pubspec.yaml
dependencies:
  uuid: ^4.0.0
