name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_BUILD_NAME: ${{ vars.FLUTTER_BUILD_NAME || '0.9.0-beta1' }}
  FLUTTER_BUILD_NUMBER: ${{ vars.FLUTTER_BUILD_NUMBER || '10001' }}

jobs:
  test:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  android:
    name: Build Android AAB
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build appbundle --release --build-name=$FLUTTER_BUILD_NAME --build-number=$FLUTTER_BUILD_NUMBER
      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error

  ios:
    name: Build iOS IPA
    runs-on: macos-14
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - name: Install pods
        run: |
          cd ios
          pod install
      - run: flutter build ipa --no-codesign --build-name=$FLUTTER_BUILD_NAME --build-number=$FLUTTER_BUILD_NUMBER
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
          if-no-files-found: error
